snpcell: "path/to/snpcell"
featurecell: "path/to/featurecell"
mafpath: "path/to/MAF_features.txt"
bimpath: "path/to/BIMS"
ldblockspath: "path/to/LAVA_LDblocks.txt"
outputcell: "path/to/output"
script_path: "path/to/run_cv2f_MAF5LDmatch_cv2f_scores.R"
chromosomes: [20, 21, 22]
pos_prefix: "UKBB_0.9_posset_LIVER_rsid.txt"
neg_prefix: "UKBB_0.01_negset_ALL_rsid.txt"
annotation_prefix: "annotation_chrmbpnet_LIVER."
output_prefix: "ukbb_0.9_0.01_liver_annotation_chrmbpnet_LIVER_lava_ld_ld_maf"
